In [1]:
import pandas as pd

In [2]:
dados = pd.read_json('ex_dados_vendas_clientes.json')
dados.head()

                                        dados_vendas
0  {'Data de venda': '06/06/2022', 'Cliente': ['@...
1  {'Data de venda': '07/06/2022', 'Cliente': ['I...
2  {'Data de venda': '08/06/2022', 'Cliente': ['I...
3  {'Data de venda': '09/06/2022', 'Cliente': ['J...
4  {'Data de venda': '10/06/2022', 'Cliente': ['M...

In [3]:
dados = pd.json_normalize(dados['dados_vendas'])

In [4]:
dados.head()

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

In [5]:
colunas = list(dados.columns)

In [6]:
dados = dados.explode(colunas[1:])
dados.reset_index(drop=True, inplace=True)

In [7]:
dados

   Data de venda             Cliente Valor da compra
0     06/06/2022     @ANA _LUCIA 321        R$ 836,5
1     06/06/2022  DieGO ARMANDIU 210       R$ 573,33
2     06/06/2022  DieGO ARMANDIU 210        R$ 392,8
3     06/06/2022  DieGO ARMANDIU 210       R$ 512,34
4     07/06/2022  Isabely JOanes 738       R$ 825,31
5     07/06/2022  Isabely JOanes 738       R$ 168,07
6     07/06/2022  Isabely JOanes 738       R$ 339,18
7     07/06/2022  Isabely JOanes 738       R$ 314,69
8     08/06/2022  Isabely JOanes 738       R$ 682,05
9     08/06/2022    JOãO Gabriel 671       R$ 386,34
10    08/06/2022  Julya meireles 914       R$ 622,65
11    08/06/2022  Julya meireles 914       R$ 630,79
12    09/06/2022  Julya meireles 914        R$ 390,3
13    09/06/2022     MaRIA Julia 444       R$ 759,16
14    09/06/2022     MaRIA Julia 444       R$ 334,47
15    09/06/2022     MaRIA Julia 444       R$ 678,78
16    10/06/2022     MaRIA Julia 444       R$ 314,24
17    10/06/2022     PEDRO PASCO 812       R$ 311,15
18    10/06/2022    Paulo castro 481       R$ 899,16
19    10/06/2022   Thiago fritzz 883       R$ 885,24

In [8]:
dados['Valor da compra'] = dados['Valor da compra'].apply(lambda x: x.replace('R$','').replace(',','.').strip())

In [9]:
import numpy as np

In [10]:
dados['Valor da compra'] = dados['Valor da compra'].astype(np.float64)

In [17]:
dados['Cliente'] = dados['Cliente'].str.replace('[^a-zA-Z ]','',regex=True).str.strip().str.upper()
dados

   Data de venda         Cliente  Valor da compra
0     06/06/2022       ANA LUCIA           836.50
1     06/06/2022  DIEGO ARMANDIU           573.33
2     06/06/2022  DIEGO ARMANDIU           392.80
3     06/06/2022  DIEGO ARMANDIU           512.34
4     07/06/2022  ISABELY JOANES           825.31
5     07/06/2022  ISABELY JOANES           168.07
6     07/06/2022  ISABELY JOANES           339.18
7     07/06/2022  ISABELY JOANES           314.69
8     08/06/2022  ISABELY JOANES           682.05
9     08/06/2022     JOO GABRIEL           386.34
10    08/06/2022  JULYA MEIRELES           622.65
11    08/06/2022  JULYA MEIRELES           630.79
12    09/06/2022  JULYA MEIRELES           390.30
13    09/06/2022     MARIA JULIA           759.16
14    09/06/2022     MARIA JULIA           334.47
15    09/06/2022     MARIA JULIA           678.78
16    10/06/2022     MARIA JULIA           314.24
17    10/06/2022     PEDRO PASCO           311.15
18    10/06/2022    PAULO CASTRO           899.16
19    10/06/2022   THIAGO FRITZZ           885.24